# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'comments_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_comments_dialog(object):
    def setupUi(self, comments_dialog):
        comments_dialog.setObjectName("comments_dialog")
        comments_dialog.resize(450, 400)
        self.verticalLayout = QtWidgets.QVBoxLayout(comments_dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout.setContentsMargins(0,0,0,0)
        self.comments_widget = QtWidgets.QWidget(comments_dialog)
        self.comments_widget.setObjectName("comments_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.comments_widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.comments_title = QtWidgets.QLabel(self.comments_widget)
        self.comments_title.setObjectName("comments_title")
        self.verticalLayout_2.addWidget(self.comments_title)
        self.comments_textEdit = QtWidgets.QTextEdit(self.comments_widget)
        self.comments_textEdit.setObjectName("comments_textEdit")
        self.verticalLayout_2.addWidget(self.comments_textEdit)
        self.verticalLayout.addWidget(self.comments_widget)
        self.buttons_bpx = QtWidgets.QWidget(comments_dialog)
        self.buttons_bpx.setObjectName("buttons_bpx")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.buttons_bpx)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.save_comment = QtWidgets.QPushButton(self.buttons_bpx)
        self.save_comment.setObjectName("save_comment")
        self.horizontalLayout.addWidget(self.save_comment)
        self.cancel_comment = QtWidgets.QPushButton(self.buttons_bpx)
        self.cancel_comment.setStyleSheet("color: red")
        self.cancel_comment.setObjectName("cancel_comment")
        self.horizontalLayout.addWidget(self.cancel_comment)
        self.verticalLayout.addWidget(self.buttons_bpx)
        self.save_comment.clicked.connect(comments_dialog.accept)  # "Save" button
        self.cancel_comment.clicked.connect(comments_dialog.reject)

        self.retranslateUi(comments_dialog)
        QtCore.QMetaObject.connectSlotsByName(comments_dialog)

    def retranslateUi(self, comments_dialog):
        _translate = QtCore.QCoreApplication.translate
        comments_dialog.setWindowTitle(_translate("comments_dialog", "Dialog"))
        self.comments_title.setText(_translate("comments_dialog", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">Comments</span></p></body></html>"))
        self.save_comment.setText(_translate("comments_dialog", "Save"))
        self.cancel_comment.setText(_translate("comments_dialog", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    comments_dialog = QtWidgets.QDialog()
    ui = Ui_comments_dialog()
    ui.setupUi(comments_dialog)
    comments_dialog.show()
    sys.exit(app.exec_())
