# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'enter_new_operation_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys


class Ui_New_operation_type(object):
    def setupUi(self, New_operation_type):
        New_operation_type.setObjectName("New_operation_type")
        New_operation_type.resize(305, 150)
        self.enter_new_operation_widget = QtWidgets.QWidget(New_operation_type)
        self.enter_new_operation_widget.setGeometry(QtCore.QRect(5, 0, 300, 150))
        self.enter_new_operation_widget.setObjectName("enter_new_operation_widget")
        self.enter_new_operation_label = QtWidgets.QLabel(self.enter_new_operation_widget)
        self.enter_new_operation_label.setGeometry(QtCore.QRect(5, 5, 300, 20))
        self.enter_new_operation_label.setObjectName("enter_new_operation_label")
        self.new_operation_buttonBox = QtWidgets.QDialogButtonBox(self.enter_new_operation_widget)
        self.new_operation_buttonBox.setGeometry(QtCore.QRect(110, 110, 180, 30))
        self.new_operation_buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.new_operation_buttonBox.setObjectName("new_operation_buttonBox")
        self.enter_new_operation_lineEdit = QtWidgets.QLineEdit(self.enter_new_operation_widget)
        self.enter_new_operation_lineEdit.setGeometry(QtCore.QRect(0, 50, 295, 40))
        self.enter_new_operation_lineEdit.setObjectName("enter_new_operation_lineEdit")

        self.retranslateUi(New_operation_type)
        QtCore.QMetaObject.connectSlotsByName(New_operation_type)

    def retranslateUi(self, New_operation_type):
        _translate = QtCore.QCoreApplication.translate
        New_operation_type.setWindowTitle(_translate("New_operation_type", "Dialog"))
        self.enter_new_operation_label.setText(_translate("New_operation_type", "<html><head/><body><p><span style=\" font-weight:600;\">Enter New Operation Type:</span></p></body></html>"))
if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_New_operation_type()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

