# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_step.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from systems_dialog import Ui_DialogSystem
from PyQt5.QtCore import pyqtSignal, Qt
from PyQt5.QtWidgets import QWidget, QDialog, QVBoxLayout, QLabel, QMessageBox
from PyQt5 import QtWidgets, QtGui
from PyQt5 import QtCore, QtGui, QtWidgets
import resources_rc
class Ui_newStep_dialog(object):
    def setupUi(self, newStep_dialog):
        newStep_dialog.setObjectName("newStep_dialog")
        newStep_dialog.resize(820, 560)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(newStep_dialog)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_8.setContentsMargins(2,0,0,0)
        
        # New Step Title
        self.new_step_title = QtWidgets.QLabel(newStep_dialog)
        self.new_step_title.setObjectName("new_step_title")
        self.new_step_title.setFixedSize(800,50)
        self.verticalLayout_8.addWidget(self.new_step_title)

        # Belonging to Operation Type (New Widget Added)
        self.belonging_to_operation_widget = QtWidgets.QWidget(newStep_dialog)
        self.belonging_to_operation_widget.setObjectName("belonging_to_operation_widget")
        self.belonging_to_operation_widget.setMaximumSize(800, 40)  # Adjust the size if necessary
        self.belonging_to_operation_widget.setContentsMargins(0,0,0,0)
        # Create a horizontal layout for this new widget
        self.horizontalLayout_belonging_to_operation = QtWidgets.QHBoxLayout(self.belonging_to_operation_widget)
        self.horizontalLayout_belonging_to_operation.setObjectName("horizontalLayout_belonging_to_operation")
        self.horizontalLayout_belonging_to_operation.setContentsMargins(0, 0, 0, 0)

        # Create a QLabel for "Belonging to Operation Type"
        self.belonging_to_operation_label = QtWidgets.QLabel(self.belonging_to_operation_widget)
        self.belonging_to_operation_label.setObjectName("belonging_to_operation_label")
        self.belonging_to_operation_label.setText("Belonging to Operation Type")
        self.belonging_to_operation_label.setStyleSheet("font-weight: bold;")  # Set the label text to bold
        self.belonging_to_operation_label.setFixedSize(330, 30)  # Adjust size if needed
        self.horizontalLayout_belonging_to_operation.addWidget(self.belonging_to_operation_label)

        # Create a QComboBox for selecting the operation type
        self.belonging_to_operation_select = QtWidgets.QComboBox(self.belonging_to_operation_widget)
        self.belonging_to_operation_select.setObjectName("belonging_to_operation_select")
        self.belonging_to_operation_select.setFixedSize(330, 30)
        self.horizontalLayout_belonging_to_operation.addWidget(self.belonging_to_operation_select)

        # Add the "Belonging to Operation Type" widget to the vertical layout
        self.verticalLayout_8.addWidget(self.belonging_to_operation_widget)

        

        # Flight Phase Step (Moved from rightSideNeContainer to verticalLayout_8)
        self.flightPhase_new_step = QtWidgets.QWidget(newStep_dialog)
        self.flightPhase_new_step.setObjectName("flightPhase_new_step")
        self.flightPhase_new_step.setMaximumSize(800, 40)  # Adjust width to match dialog
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.flightPhase_new_step)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.flightPhase_title = QtWidgets.QLabel(self.flightPhase_new_step)
        self.flightPhase_title.setObjectName("flightPhase_title")
        self.flightPhase_title.setFixedSize(330,30)
        self.horizontalLayout.addWidget(self.flightPhase_title)
        self.flightPhase_select = QtWidgets.QComboBox(self.flightPhase_new_step)
        self.flightPhase_select.setObjectName("flightPhase_select")
        self.flightPhase_select.setFixedSize(330,30)
        self.horizontalLayout.addWidget(self.flightPhase_select)
        self.verticalLayout_8.addWidget(self.flightPhase_new_step) 
         # Now added to the dialog's main layout
        # Create a new widget with horizontal layout for the "Belonging to Procedure" section
        self.belonging_to_procedure_widget = QtWidgets.QWidget(newStep_dialog)
        self.belonging_to_procedure_widget.setObjectName("belonging_to_procedure_widget")
        self.belonging_to_procedure_widget.setMaximumSize(800, 40)  # Adjust the size if necessary

      # Create a horizontal layout for this new widget
        self.horizontalLayout_belonging_to_procedure = QtWidgets.QHBoxLayout(self.belonging_to_procedure_widget)
        self.horizontalLayout_belonging_to_procedure.setObjectName("horizontalLayout_belonging_to_procedure")
        self.horizontalLayout_belonging_to_procedure.setContentsMargins(0, 0, 0, 0)

      # Create a QLabel for "Belonging to Procedure"
        self.belonging_to_procedure_label = QtWidgets.QLabel(self.belonging_to_procedure_widget)
        self.belonging_to_procedure_label.setObjectName("belonging_to_procedure_label")
        self.belonging_to_procedure_label.setText("Belonging to Procedure")
        self.belonging_to_procedure_label.setStyleSheet("font-weight: bold;")  # Set the label text to bold
        self.belonging_to_procedure_label.setFixedSize(330, 30)  # Adjust size if needed
        self.horizontalLayout_belonging_to_procedure.addWidget(self.belonging_to_procedure_label)

        # Create a QComboBox for selecting the procedure
        self.belonging_to_procedure_select = QtWidgets.QComboBox(self.belonging_to_procedure_widget)
        self.belonging_to_procedure_select.setObjectName("belonging_to_procedure_select")
        self.belonging_to_procedure_select.setFixedSize(330, 30)
        self.horizontalLayout_belonging_to_procedure.addWidget(self.belonging_to_procedure_select)

        # Add the "Belonging to Procedure" widget to the vertical layout
        self.verticalLayout_8.addWidget(self.belonging_to_procedure_widget) 

        # New Big Box (Now without flightPhase_new_step)
        self.newBigBox = QtWidgets.QWidget(newStep_dialog)
        self.newBigBox.setObjectName("newBigBox")
        self.newBigBox.setMaximumSize(820, 450)



        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.newBigBox)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.horizontalLayout_17.setContentsMargins(0,0,0,0)

        self.verticalLayout_8.addWidget(self.newBigBox)

        

        # Right Side Container
        self.rightSideNeContainer = QtWidgets.QWidget(self.newBigBox)
        self.rightSideNeContainer.setObjectName("rightSideNeContainer")
        self.rightSideNeContainer.setMaximumSize(330, 450)
        self.verticalLayout = QtWidgets.QVBoxLayout(self.rightSideNeContainer)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)

        # Object Widget
        self.object_widget = QtWidgets.QWidget(self.rightSideNeContainer)
        self.object_widget.setObjectName("object_widget")
        self.object_widget.setMaximumSize(320,80)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.object_widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0,0,0,0)
        self.objectLabel = QtWidgets.QLabel(self.object_widget)
        self.objectLabel.setObjectName("objectLabel")
        self.objectLabel.setMaximumSize(100,80)
        self.horizontalLayout_2.addWidget(self.objectLabel)
        self.new_object = QtWidgets.QLineEdit(self.object_widget)
        self.new_object.setObjectName("new_object")
        self.new_object.setMaximumSize(200,30)
        self.horizontalLayout_2.addWidget(self.new_object)
        self.verticalLayout.addWidget(self.object_widget)

        # Action New Box
        self.actionNewBox = QtWidgets.QWidget(self.rightSideNeContainer)
        self.actionNewBox.setObjectName("actionNewBox")
        self.actionNewBox.setMaximumSize(320,80)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.actionNewBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(0,0,0,0)
        self.action_title = QtWidgets.QLabel(self.actionNewBox)
        self.action_title.setObjectName("action_title")
        self.action_title.setMaximumSize(100,80)
        self.horizontalLayout_3.addWidget(self.action_title)
        self.action_new = QtWidgets.QLineEdit(self.actionNewBox)
        self.action_new.setObjectName("action_new")
        self.action_new.setMaximumSize(200,30)
        self.horizontalLayout_3.addWidget(self.action_new)
        self.verticalLayout.addWidget(self.actionNewBox)

        # Executed By Box
        self.executedByNewBox = QtWidgets.QWidget(self.rightSideNeContainer)
        self.executedByNewBox.setObjectName("executedByNewBox")
        self.executedByNewBox.setMaximumSize(320,80)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.executedByNewBox)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_4.setContentsMargins(0,0,0,0)
        self.executedBy_title = QtWidgets.QLabel(self.executedByNewBox)
        self.executedBy_title.setObjectName("executedBy_title")
        self.executedBy_title.setMaximumSize(100,80)
        self.horizontalLayout_4.addWidget(self.executedBy_title)
        self.executedBy_new = QtWidgets.QLineEdit(self.executedByNewBox)
        self.executedBy_new.setObjectName("executedBy_new")
        self.executedBy_new.setMaximumSize(200,30)
        self.horizontalLayout_4.addWidget(self.executedBy_new)
        self.verticalLayout.addWidget(self.executedByNewBox)
        self.horizontalLayout_17.addWidget(self.rightSideNeContainer)

        # Left Side Container
        self.leftSideNewBox = QtWidgets.QWidget(self.newBigBox)
        self.leftSideNewBox.setObjectName("leftSideNewBox")
        self.leftSideNewBox.setMaximumSize(450,450)
        self.leftSideNewBox.setContentsMargins(0,0,0,0)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.leftSideNewBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0,0,0,0)
        

        # Step Position
        self.stepPositionNewBox = QtWidgets.QWidget(self.leftSideNewBox)
        self.stepPositionNewBox.setObjectName("stepPositionNewBox")
        self.stepPositionNewBox.setMaximumSize(450,80)
        #self.stepPositionNewBox.setContentsMargins(0,0,0,0)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.stepPositionNewBox)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.stepPosition_title = QtWidgets.QLabel(self.stepPositionNewBox)
        self.stepPosition_title.setObjectName("stepPosition_title")
        self.stepPosition_title.setMaximumSize(140,80)
        self.horizontalLayout_5.addWidget(self.stepPosition_title)
        self.horizontalLayout_5.setContentsMargins(0,0,0,0)
        self.spinBox_step_position = QtWidgets.QSpinBox(self.stepPositionNewBox)
        self.spinBox_step_position.setObjectName("spinBox_step_position")
        self.spinBox_step_position.setMaximumSize(255,30)
        self.horizontalLayout_5.addWidget(self.spinBox_step_position)
        self.verticalLayout_2.addWidget(self.stepPositionNewBox)
        

        # Physical Features Box
        self.physicalNewBox = QtWidgets.QWidget(self.leftSideNewBox)
        self.physicalNewBox.setObjectName("physicalNewBox")
        #self.physicalNewBox.setContentsMargins(0,0,0,0)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.physicalNewBox)
        self.physicalNewBox.setMaximumSize(450,80)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.physicalFeatures_title = QtWidgets.QLabel(self.physicalNewBox)
        self.physicalFeatures_title.setObjectName("physicalFeatures_title")
        self.physicalFeatures_title.setMaximumSize(155,80)
        self.horizontalLayout_6.addWidget(self.physicalFeatures_title)
        self.horizontalLayout_6.setContentsMargins(0,0,0,0)
        self.parameterPhysicalFeatures = QtWidgets.QLineEdit(self.physicalNewBox)
        self.parameterPhysicalFeatures.setObjectName("parameterPhysicalFeatures")
        self.parameterPhysicalFeatures.setMaximumSize(135,35)
        self.horizontalLayout_6.addWidget(self.parameterPhysicalFeatures)
        self.valuePhysicalFeatures = QtWidgets.QLineEdit(self.physicalNewBox)
        self.valuePhysicalFeatures.setObjectName("valuePhysicalFeatures")
        self.valuePhysicalFeatures.setMaximumSize(100,35)
        self.horizontalLayout_6.addWidget(self.valuePhysicalFeatures)
        self.verticalLayout_2.addWidget(self.physicalNewBox)

        # Output Parameters Box
        self.outPutNewContainer = QtWidgets.QWidget(self.leftSideNewBox)
        self.outPutNewContainer.setObjectName("outPutNewContainer")
        #self.outPutNewContainer.setContentsMargins(0,0,0,0)
        self.outPutNewContainer.setMaximumSize(450,80)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.outPutNewContainer)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_7.setContentsMargins(0,0,0,0)
        self.outputParameters_label = QtWidgets.QLabel(self.outPutNewContainer)
        self.outputParameters_label.setObjectName("outputParameters_label")
        self.outputParameters_label.setMaximumSize(170,80)
        self.horizontalLayout_7.addWidget(self.outputParameters_label)
        self.outputParameters_new = QtWidgets.QLineEdit(self.outPutNewContainer)
        self.outputParameters_new.setObjectName("outputParameters_new")
        self.outputParameters_new.setMaximumSize(260,30)
        self.horizontalLayout_7.addWidget(self.outputParameters_new)
        self.verticalLayout_2.addWidget(self.outPutNewContainer)
        self.horizontalLayout_17.addWidget(self.leftSideNewBox)
        
        self.verticalLayout_8.addWidget(self.newBigBox)
        # Horizontal Requirement Display
        #self.horizontalReqDisplay = QtWidgets.QWidget(newStep_dialog)
        #self.horizontalReqDisplay.setMaximumSize(800,100)
        #self.horizontalReqDisplay.setObjectName("horizontalReqDisplay")
        #self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.horizontalReqDisplay)
        #self.horizontalLayout_16.setObjectName("horizontalLayout_16")

        # Provides Vertical Container
        #self.providesVerticalContainer = QtWidgets.QWidget(self.horizontalReqDisplay)
        #self.providesVerticalContainer.setObjectName("providesVerticalContainer")
        #self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.providesVerticalContainer)
        #self.verticalLayout_5.setObjectName("verticalLayout_5")
        #self.provides_label = QtWidgets.QLabel(self.providesVerticalContainer)
        #self.provides_label.setObjectName("provides_label")
        #self.provides_label.setStyleSheet("font-weight: bold;") 
        #self.verticalLayout_5.addWidget(self.provides_label)
        #self.provides_display = QtWidgets.QLabel(self.providesVerticalContainer)
        #self.provides_display.setObjectName("provides_display")
        #self.verticalLayout_5.addWidget(self.provides_display)
        #self.horizontalLayout_16.addWidget(self.providesVerticalContainer)

        # Requires Vertical Container
        #self.requiresVerticalContainer = QtWidgets.QWidget(self.horizontalReqDisplay)
        #self.requiresVerticalContainer.setObjectName("requiresVerticalContainer")
        #self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.requiresVerticalContainer)
        #self.verticalLayout_6.setObjectName("verticalLayout_6")
        #self.requires_title = QtWidgets.QLabel(self.requiresVerticalContainer)
        #self.requires_title.setObjectName("requires_title")
        #self.requires_title.setStyleSheet("font-weight: bold;")
        #self.verticalLayout_6.addWidget(self.requires_title)
        #self.requires_display = QtWidgets.QLabel(self.requiresVerticalContainer)
        #self.requires_display.setObjectName("requires_display")
        #self.requires_display.setText("")
        #self.verticalLayout_6.addWidget(self.requires_display)
        #self.horizontalLayout_16.addWidget(self.requiresVerticalContainer)

        # Turns Off Vertical Container
        #self.turnsOffVerticalContainer = QtWidgets.QWidget(self.horizontalReqDisplay)
        #self.turnsOffVerticalContainer.setObjectName("turnsOffVerticalContainer")
        #self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.turnsOffVerticalContainer)
        #self.verticalLayout_7.setObjectName("verticalLayout_7")
        #self.turnsoff_label = QtWidgets.QLabel(self.turnsOffVerticalContainer)
        #self.turnsoff_label.setObjectName("turnsoff_label")
        #self.turnsoff_label.setStyleSheet("font-weight: bold;")
        #self.verticalLayout_7.addWidget(self.turnsoff_label)
        #self.turnsoff_display = QtWidgets.QLabel(self.turnsOffVerticalContainer)
        #self.turnsoff_display.setObjectName("turnsoff_display")
        #self.verticalLayout_7.addWidget(self.turnsoff_display)
        #self.horizontalLayout_16.addWidget(self.turnsOffVerticalContainer)

        # Systems Button
        #self.pushButton_systems = QtWidgets.QPushButton(self.horizontalReqDisplay)
        #self.pushButton_systems.setObjectName("pushButton_systems")
        
        #self.horizontalLayout_16.addWidget(self.pushButton_systems)
        
        # Add the horizontalReqDisplay widget under newBigBox
        #self.verticalLayout_8.addWidget(self.horizontalReqDisplay)
        
        # Dialog Buttons (OK/Cancel)
        self.buttonBox_new_step = QtWidgets.QDialogButtonBox(newStep_dialog)
        self.buttonBox_new_step.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox_new_step.setObjectName("buttonBox_new_step")
        self.buttonBox_new_step.setMaximumSize(800,40)
        self.verticalLayout_8.addWidget(self.buttonBox_new_step)

        self.retranslateUi(newStep_dialog)
        QtCore.QMetaObject.connectSlotsByName(newStep_dialog)

    def retranslateUi(self, newStep_dialog):
        _translate = QtCore.QCoreApplication.translate
        newStep_dialog.setWindowTitle(_translate("newStep_dialog", "Dialog"))
        self.new_step_title.setText(_translate("newStep_dialog", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">New Step</span></p></body></html>"))
        self.flightPhase_title.setText(_translate("newStep_dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Belonging to flight phase</span></p></body></html>"))
        self.objectLabel.setText(_translate("newStep_dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Object</span></p></body></html>"))
        self.action_title.setText(_translate("newStep_dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Action</span></p></body></html>"))
        self.executedBy_title.setText(_translate("newStep_dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Executed By</span></p></body></html>"))
        self.stepPosition_title.setText(_translate("newStep_dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Step position </span></p></body></html>"))
        self.physicalFeatures_title.setText(_translate("newStep_dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Physical Features</span></p></body></html>"))
        #self.provides_label.setText(_translate("newStep_dialog", "Provides:"))
        #self.requires_title.setText(_translate("newStep_dialog", "Requires:"))
        #self.turnsoff_label.setText(_translate("newStep_dialog", "Turns Off:"))
        #self.pushButton_systems.setText(_translate("newStep_dialog", "Edit Systems"))
        self.parameterPhysicalFeatures.setPlaceholderText(_translate("newStep_dialog", "Enter Parameter"))
        self.valuePhysicalFeatures.setPlaceholderText(_translate("newStep_dialog", "Enter Value"))
        self.outputParameters_label.setText(_translate("newStep_dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Output Parameters</span></p></body></html>"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    newStep_dialog = QtWidgets.QDialog()
    ui = Ui_newStep_dialog()
    ui.setupUi(newStep_dialog)
    newStep_dialog.show()
    sys.exit(app.exec_())
