# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rationale_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import resources_rc


class Ui_Rationale_Dialog(object):
    def setupUi(self, Rationale_Dialog):
        Rationale_Dialog.setObjectName("Rationale_Dialog")
        Rationale_Dialog.resize(450, 400)
        Rationale_Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Rationale_Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout.setContentsMargins(0,0,0,0)
        self.rationale_widget = QtWidgets.QWidget(Rationale_Dialog)
        self.rationale_widget.setObjectName("rationale_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.rationale_widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.rationale_widget)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.textEdit = QtWidgets.QTextEdit(self.rationale_widget)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_2.addWidget(self.textEdit)
        self.verticalLayout.addWidget(self.rationale_widget)
        self.widget = QtWidgets.QWidget(Rationale_Dialog)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setStyleSheet("color: red")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout.addWidget(self.widget)
        self.pushButton.clicked.connect(Rationale_Dialog.accept)  # "Save" button
        self.pushButton_2.clicked.connect(Rationale_Dialog.reject)

        self.retranslateUi(Rationale_Dialog)
        QtCore.QMetaObject.connectSlotsByName(Rationale_Dialog)

    def retranslateUi(self, Rationale_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Rationale_Dialog.setWindowTitle(_translate("Rationale_Dialog", "Dialog"))
        self.label.setText(_translate("Rationale_Dialog", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">Rationale</span></p></body></html>"))
        self.pushButton.setText(_translate("Rationale_Dialog", "Save"))
        self.pushButton_2.setText(_translate("Rationale_Dialog", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Rationale_Dialog = QtWidgets.QDialog()
    ui = Ui_Rationale_Dialog()
    ui.setupUi(Rationale_Dialog)
    Rationale_Dialog.show()
    sys.exit(app.exec_())
