# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'set_input_req_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from set_input_req_dialog11 import Ui_setInputReqDialog  # Import the dialog class
from system_req_input_row import Ui_setReqInputRow  # Import the form with labels


class Ui_SetInputReqWidget(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setFixedSize(1500, 260)
        self.checkpoint_widget = QtWidgets.QWidget(Form)
        self.checkpoint_widget.setGeometry(QtCore.QRect(0, 5, 1500, 250))
        self.checkpoint_widget.setStyleSheet("QWidget {\n"
                                             "    background-color: rgb(255, 255, 255);\n"
                                             "    border: 3px solid red;\n"
                                             "    border-color: red;\n"
                                             "    border-radius: 3px;\n"
                                             "}")
        self.checkpoint_widget.setObjectName("checkpoint_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.checkpoint_widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        
        self.container = QtWidgets.QWidget(self.checkpoint_widget)
        self.container.setStyleSheet("QWidget{ border: 3px solid red; background-color: rgb(255, 255, 255);}")
        self.container.setObjectName("container")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.container)
        self.horizontalLayout.setObjectName("horizontalLayout")
        
        self.checnpoint_label = QtWidgets.QLabel(self.container)
        self.checnpoint_label.setStyleSheet("QLabel { background-color: rgb(255, 255, 255); border: none; color: red; }")
        self.checnpoint_label.setObjectName("checnpoint_label")
        self.horizontalLayout.addWidget(self.checnpoint_label)
        
        self.inputlistbox = QtWidgets.QWidget(self.container)
        self.inputlistbox.setStyleSheet("QWidget{ border: none; }")
        self.inputlistbox.setObjectName("inputlistbox")
        self.inputlistbox.setMaximumSize(800, 300)

        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.inputlistbox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_3.setSpacing(0)
        
        self.req_input_header = QtWidgets.QLabel(self.inputlistbox)
        self.req_input_header.setStyleSheet("QLabel{ border: 1px solid; border-color: red; background-color: rgb(255, 255, 255); border-radius: 0px; }")
        self.req_input_header.setObjectName("req_input_header")
        self.verticalLayout_3.addWidget(self.req_input_header)
        
        self.req_input_listWidget = QtWidgets.QListWidget(self.inputlistbox)
        self.req_input_listWidget.setStyleSheet("QListWidget{ border: 1px solid; border-color: red; background-color: rgb(255, 255, 255); border-radius: 0px; }")
        self.req_input_listWidget.setObjectName("req_input_listWidget")
        self.req_input_listWidget.setMaximumSize(800, 300)
        self.verticalLayout_3.addWidget(self.req_input_listWidget)
        
        self.horizontalLayout.addWidget(self.inputlistbox)
        
        self.inputButtonBox = QtWidgets.QWidget(self.container)
        self.inputButtonBox.setStyleSheet("QWidget{ border: none; }")
        self.inputButtonBox.setObjectName("inputButtonBox")
        
        self.verticalLayout = QtWidgets.QVBoxLayout(self.inputButtonBox)
        self.verticalLayout.setObjectName("verticalLayout")
        
        self.inputButton = QtWidgets.QPushButton(self.inputButtonBox)
        self.inputButton.setMouseTracking(True)
        self.inputButton.setMinimumSize(250,20)
        self.inputButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.inputButton.setStyleSheet("QPushButton { border: 2px solid; border-color: red; color: black; } QPushButton:hover { background-color: darkgray; }")
        self.inputButton.setCheckable(False)
        self.inputButton.setAutoDefault(False)
        self.inputButton.setObjectName("inputButton")
        self.verticalLayout.addWidget(self.inputButton)
        
        self.horizontalLayout.addWidget(self.inputButtonBox)
        self.deleteCheckpointButton = QtWidgets.QPushButton(self.inputButtonBox)
        self.deleteCheckpointButton.setMouseTracking(True)
        self.deleteCheckpointButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.deleteCheckpointButton.setStyleSheet("QPushButton { border: 2px solid; border-color: red; color: black; } QPushButton:hover { background-color: darkgray; }")
        self.deleteCheckpointButton.setCheckable(False)
        self.deleteCheckpointButton.setAutoDefault(False)
        self.deleteCheckpointButton.setObjectName("deleteCheckpointButton")
        self.deleteCheckpointButton.setText("Delete Checkpoint")  # Set the text for the button
        self.horizontalLayout.addWidget(self.deleteCheckpointButton)
        self.verticalLayout_2.addWidget(self.container)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        #self.deleteCheckpointButton.clicked.connect(self.delete_checkpoint_with_confirmation)
        # Connect the input button to the method that opens the dialog
        #self.inputButton.clicked.connect(self.open_input_dialog)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        self.checnpoint_label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">Checkpoint</span></p></body></html>"))
        self.req_input_header.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Input</span></p></body></html>"))
        self.inputButton.setText(_translate("Form", "Set Required Input Parameters"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_SetInputReqWidget()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
