# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'set_input_req_dialog11.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_setInputReqDialog(object):
    def setupUi(self, setInputReqDialog):
        setInputReqDialog.setObjectName("setInputReqDialog")
        setInputReqDialog.resize(500, 300)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(setInputReqDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(5,5,0,5)
        self.setInputTitle = QtWidgets.QLabel(setInputReqDialog)
        self.setInputTitle.setObjectName("setInputTitle")
        self.verticalLayout_2.addWidget(self.setInputTitle)
        self.widget = QtWidgets.QWidget(setInputReqDialog)
        self.widget.setObjectName("widget")
        self.widget.setMinimumSize(500,280)
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout.setContentsMargins(0,0,0,0)
        self.checkpointBox = QtWidgets.QWidget(self.widget)
        self.checkpointBox.setObjectName("systemBox")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.checkpointBox)
        self.horizontalLayout_4.setObjectName("horizontalLayout")
        self.checkpointName = QtWidgets.QLabel(self.checkpointBox)
        self.checkpointName.setObjectName("checkpointName")
        self.checkpointName.setFixedSize(140,30)
        self.horizontalLayout_4.addWidget(self.checkpointName)
        self.checkpointInputLineEdit = QtWidgets.QLineEdit(self.checkpointBox)
        #self.checkpointInputLineEdit = QtWidgets.QLineEdit(self.checkpointBox)
        self.checkpointInputLineEdit.setPlaceholderText("Enter checkpoint name")

        self.checkpointInputLineEdit.setObjectName("checkpointInputLineEdit")
        self.checkpointInputLineEdit.setMaximumSize(350,40)
        self.horizontalLayout_4.addWidget(self.checkpointInputLineEdit)
        self.verticalLayout.addWidget(self.checkpointBox)
        self.systemBox = QtWidgets.QWidget(self.widget)
        self.systemBox.setObjectName("systemBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.systemBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.systemName = QtWidgets.QLabel(self.systemBox)
        self.systemName.setObjectName("systemName")
        self.systemName.setFixedSize(140,30)
        self.horizontalLayout.addWidget(self.systemName)
        self.systemInputLineEdit = QtWidgets.QLineEdit(self.systemBox)
        self.systemInputLineEdit.setObjectName("systemInputLineEdit")
        self.systemInputLineEdit.setMaximumSize(350,40)
        self.horizontalLayout.addWidget(self.systemInputLineEdit)
        self.verticalLayout.addWidget(self.systemBox)
        self.parameterBox = QtWidgets.QWidget(self.widget)
        self.parameterBox.setObjectName("parameterBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.parameterBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ParameterLabel = QtWidgets.QLabel(self.parameterBox)
        self.ParameterLabel.setObjectName("ParameterLabel")
        self.ParameterLabel.setFixedSize(140,30)
        self.horizontalLayout_2.addWidget(self.ParameterLabel)
        self.parameterLineEdit = QtWidgets.QLineEdit(self.parameterBox)
        self.parameterLineEdit.setObjectName("parameterLineEdit")
        self.parameterLineEdit.setMaximumSize(350,40)
        self.horizontalLayout_2.addWidget(self.parameterLineEdit)
        self.verticalLayout.addWidget(self.parameterBox)
        #self.unitBox = QtWidgets.QWidget(self.widget)
        #self.unitBox.setObjectName("unitBox")
        #self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.unitBox)
        #self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        #self.unitLabel = QtWidgets.QLabel(self.unitBox)
        #self.unitLabel.setObjectName("unitLabel")
        #self.unitLabel.setFixedSize(140,30)
        #self.horizontalLayout_3.addWidget(self.unitLabel)
        #self.unitLineEdit = QtWidgets.QLineEdit(self.unitBox)
        #self.unitLineEdit.setMaximumSize(350,40)
        #self.horizontalLayout_3.addWidget(self.unitLineEdit)
        #self.verticalLayout.addWidget(self.unitBox)
        self.verticalLayout_2.addWidget(self.widget)
        self.inputButtonBox = QtWidgets.QDialogButtonBox(setInputReqDialog)
        self.inputButtonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.inputButtonBox.setObjectName("inputButtonBox")
        self.verticalLayout_2.addWidget(self.inputButtonBox)

        self.retranslateUi(setInputReqDialog)
        QtCore.QMetaObject.connectSlotsByName(setInputReqDialog)

    def retranslateUi(self, setInputReqDialog):
        _translate = QtCore.QCoreApplication.translate
        setInputReqDialog.setWindowTitle(_translate("setInputReqDialog", "Dialog"))
        self.setInputTitle.setText(_translate("setInputReqDialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Set Input Requirements </span></p></body></html>"))
        self.systemName.setText(_translate("setInputReqDialog", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">System State </span></p></body></html>"))
        self.ParameterLabel.setText(_translate("setInputReqDialog", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">Person State</span></p></body></html>"))
        #self.unitLabel.setText(_translate("setInputReqDialog", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">Unit (Optional)</span></p></body></html>"))
        self.checkpointName.setText(_translate("setInputReqDialog", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">Checkpoint  </span></p></body></html>"))
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    setInputReqDialog = QtWidgets.QDialog()
    ui = Ui_setInputReqDialog()
    ui.setupUi(setInputReqDialog)
    setInputReqDialog.show()
    sys.exit(app.exec_())
