# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'system_req_input_row.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_setReqInputRow(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 25)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.sys_input_req_row = QtWidgets.QWidget(Form)
        self.sys_input_req_row.setObjectName("sys_input_req_row")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.sys_input_req_row)
        self.horizontalLayout.setObjectName("horizontalLayout")
            # System Name Label
        self.checkpointName = QtWidgets.QLabel(self.sys_input_req_row)
        self.checkpointName.setFrameShape(QtWidgets.QFrame.Box)
        self.checkpointName.setObjectName("checkpointName")
        self.checkpointName.setAlignment(QtCore.Qt.AlignCenter)  # Center the text
        self.horizontalLayout.addWidget(self.checkpointName)
        
        # System Name Label
        self.systemName = QtWidgets.QLabel(self.sys_input_req_row)
        self.systemName.setFrameShape(QtWidgets.QFrame.Box)
        self.systemName.setObjectName("systemName")
        self.systemName.setAlignment(QtCore.Qt.AlignCenter)  # Center the text
        self.horizontalLayout.addWidget(self.systemName)
        
        # Parameter Label
        self.parameterLbael = QtWidgets.QLabel(self.sys_input_req_row)
        self.parameterLbael.setFrameShape(QtWidgets.QFrame.Box)
        self.parameterLbael.setObjectName("parameterLbael")
        self.parameterLbael.setAlignment(QtCore.Qt.AlignCenter)  # Center the text
        self.horizontalLayout.addWidget(self.parameterLbael)
        
        # Unit Label
        #self.unitLabel = QtWidgets.QLabel(self.sys_input_req_row)
        #self.unitLabel.setFrameShape(QtWidgets.QFrame.Box)
        #self.unitLabel.setObjectName("unitLabel")
        #self.unitLabel.setAlignment(QtCore.Qt.AlignCenter)  # Center the text
        #self.horizontalLayout.addWidget(self.unitLabel)
        
        self.verticalLayout.addWidget(self.sys_input_req_row)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        #Form.setWindowTitle(_translate("Form", "Form"))
        self.systemName.setText(_translate("Form", "System"))
        self.checkpointName.setText(_translate("Form","<html><head/><body><p><span style=\" font-weight:600;\">Checkpoint Name</span></p></body></html>"))
        self.parameterLbael.setText(_translate("Form", "Person State"))
        #self.unitLabel.setText(_translate("Form", "Unit"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_setReqInputRow()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
