# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'systems_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from systen_row import Ui_systemsRows



class Ui_DialogSystem(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setFixedSize(610, 500)
        Dialog.setStyleSheet("""
            QDialog, QWidget, QFrame, QLabel, QPushButton, QCheckBox, QLineEdit, QDialogButtonBox {
                background-color: white;
            }
            QScrollArea {
                background-color: white;
            }
            QScrollArea > QWidget {
                background-color: white;
            }
            QHeaderView::section {
                background-color: white;
            }
        """)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(5,0,5,0)
        self.requirementsHeader = QtWidgets.QWidget(Dialog)
        self.requirementsHeader.setObjectName("requirementsHeader")

        self.horizontalLayout = QtWidgets.QHBoxLayout(self.requirementsHeader)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout.setContentsMargins(0,0,0,0)
        self.systemsTitle = QtWidgets.QLabel(self.requirementsHeader)
        self.systemsTitle.setObjectName("systemsTitle")
        
        self.horizontalLayout.addWidget(self.systemsTitle)
        spacerItem = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.ProvidesLabel = QtWidgets.QLabel(self.requirementsHeader)
        self.ProvidesLabel.setObjectName("ProvidesLabel")
        self.horizontalLayout.addWidget(self.ProvidesLabel)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.requiresLabel = QtWidgets.QLabel(self.requirementsHeader)
        self.requiresLabel.setObjectName("requiresLabel")
        self.horizontalLayout.addWidget(self.requiresLabel)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.turnsOffLabel = QtWidgets.QLabel(self.requirementsHeader)
        self.turnsOffLabel.setObjectName("turnsOffLabel")
        self.horizontalLayout.addWidget(self.turnsOffLabel)
        spacerItem3 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout_3.addWidget(self.requirementsHeader)
        self.systemsScrollArea = QtWidgets.QScrollArea(Dialog)
        self.systemsScrollArea.setWidgetResizable(True)
        self.systemsScrollArea.setContentsMargins(0,0,0,0)
        self.systemsScrollArea.setObjectName("systemsScrollArea")
        self.systemsScrollArea.resize(570,400)
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        #self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 450, 228))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout.setContentsMargins(0,0,5,0)
        self.systemsContainer = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.systemsContainer.setObjectName("systemsContainer")
        # Set the vertical layout inside the scroll area to align top
        #self.verticalLayout_2.setAlignment(QtCore.Qt.AlignTop)

        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.systemsContainer)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
       
        self.systemsLabel = QtWidgets.QLabel(self.systemsContainer)
        self.systemsLabel.setObjectName("systemsLabel")
        self.systemsLabel.setMaximumSize(570,50)
        self.systemsLabel.setContentsMargins(0,0,0,0)
        # Add the label to the layout and align it to the top-left
        
        self.verticalLayout_2.setContentsMargins(0,0,0,0)
        self.verticalLayout_2.addWidget(self.systemsLabel, alignment=QtCore.Qt.AlignTop | QtCore.Qt.AlignLeft)


        self.verticalLayout_2.addWidget(self.systemsLabel)
        self.verticalLayout.addWidget(self.systemsContainer)
        self.systemsScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.systemsScrollArea)
        self.systemsButtonsContainer = QtWidgets.QFrame(Dialog)
        self.systemsButtonsContainer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.systemsButtonsContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.systemsButtonsContainer.setObjectName("systemsButtonsContainer")
        self.systemsContainer.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.setAlignment(QtCore.Qt.AlignTop)

        

        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.systemsButtonsContainer)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.systemsButtonsContainer)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setFixedSize(100,40)
        self.pushButton.setText("New System")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.newSystemLineEdit = QtWidgets.QLineEdit(self.systemsButtonsContainer)
        self.newSystemLineEdit.setFixedSize(250,40)
        self.newSystemLineEdit.setObjectName("newSystemLineEdit")
        self.newSystemLineEdit.setPlaceholderText("Enter new system name") 
        
       

        self.horizontalLayout_2.addWidget(self.newSystemLineEdit)
        self.horizontalLayout_2.setContentsMargins(0,5,0,5)
        spacerItem4 = QtWidgets.QSpacerItem(0, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.buttonBox_system_dialog = QtWidgets.QDialogButtonBox(self.systemsButtonsContainer)
        self.buttonBox_system_dialog.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox_system_dialog.setObjectName("buttonBox_system_dialog")
        self.horizontalLayout_2.addWidget(self.buttonBox_system_dialog)
        self.verticalLayout_3.addWidget(self.systemsButtonsContainer)
        

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        



    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.requirementsHeader.setWhatsThis(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.systemsTitle.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">Systems</span></p></body></html>"))
        self.ProvidesLabel.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:9pt; font-weight:600;\">Provides</span></p></body></html>"))
        self.requiresLabel.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:9pt; font-weight:600;\">Requires</span></p></body></html>"))
        self.turnsOffLabel.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:9pt; font-weight:600;\">Turns Off</span></p></body></html>"))
        self.systemsLabel.setText(_translate("Dialog", ""))
        #self.pushButton.setText(_translate("Dialog", "New System"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_DialogSystem()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
