# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'type_of_operation.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TypeOfOperationDialog(object):
    def setupUi(self, TypeOfOperationDialog):
        TypeOfOperationDialog.setObjectName("TypeOfOperationDialog")
        TypeOfOperationDialog.resize(500, 290)
        self.typeOfOperationBox = QtWidgets.QWidget(TypeOfOperationDialog)
        self.typeOfOperationBox.setGeometry(QtCore.QRect(5, 5, 500, 280))
        self.typeOfOperationBox.setObjectName("typeOfOperationBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.typeOfOperationBox)
        self.verticalLayout.setContentsMargins(0, 0, 10, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.typeOperationBox_1 = QtWidgets.QWidget(self.typeOfOperationBox)
        self.typeOperationBox_1.setObjectName("typeOperationBox_1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.typeOperationBox_1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.operation_label = QtWidgets.QLabel(self.typeOperationBox_1)
        self.operation_label.setObjectName("operation_label")
        self.operation_label.setMinimumSize(130,30)
        self.horizontalLayout.addWidget(self.operation_label)
        self.operation_select = QtWidgets.QComboBox(self.typeOperationBox_1)
        self.operation_select.setObjectName("operation_select")
        self.operation_select.setMinimumSize(200,30)
        
        self.horizontalLayout.addWidget(self.operation_select)
        self.select_operation = QtWidgets.QPushButton(self.typeOperationBox_1)
        self.select_operation.setObjectName("select_operation")
        self.horizontalLayout.addWidget(self.select_operation)
        self.verticalLayout.addWidget(self.typeOperationBox_1)
        self.typeOfOperation_2 = QtWidgets.QWidget(self.typeOfOperationBox)
        self.typeOfOperation_2.setObjectName("typeOfOperation_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.typeOfOperation_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.operation = QtWidgets.QLabel(self.typeOfOperation_2)
        self.operation.setObjectName("operation")
        self.operation.setMinimumSize(130,30)

        self.horizontalLayout_2.addWidget(self.operation)
        self.operation_enter = QtWidgets.QLineEdit(self.typeOfOperation_2)
        self.operation_enter.setObjectName("operation_enter")
        self.operation_enter.setMinimumSize(200,30)
        self.horizontalLayout_2.addWidget(self.operation_enter)
        self.select_operation_2 = QtWidgets.QPushButton(self.typeOfOperation_2)
        self.select_operation_2.setObjectName("select_operation_2")
        self.horizontalLayout_2.addWidget(self.select_operation_2)
        self.verticalLayout.addWidget(self.typeOfOperation_2)
        self.widget_4 = QtWidgets.QWidget(self.typeOfOperationBox)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.missionTypeLabel = QtWidgets.QLabel(self.widget_4)
        self.missionTypeLabel.setObjectName("missionTypeLabel")
        self.missionTypeLabel.setMinimumSize(130,30)
        self.horizontalLayout_3.addWidget(self.missionTypeLabel)
        self.missionLineEdit = QtWidgets.QLineEdit(self.widget_4)
        self.missionLineEdit.setObjectName("missionLineEdit")
        self.missionLineEdit.setMinimumSize(200,30)
        self.horizontalLayout_3.addWidget(self.missionLineEdit)
        self.selectMission = QtWidgets.QPushButton(self.widget_4)
        self.selectMission.setObjectName("selectMission")
        self.horizontalLayout_3.addWidget(self.selectMission)
        self.verticalLayout.addWidget(self.widget_4)
        #self.delete_operation_button = QtWidgets.QPushButton(self.typeOfOperationBox)
       # self.delete_operation_button.setText("Delete Operation")
       # self.verticalLayout.addWidget(self.delete_operation_button)
        self.buttonBox_operation = QtWidgets.QDialogButtonBox(self.typeOfOperationBox)
        self.buttonBox_operation.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox_operation.setObjectName("buttonBox_operation")


        self.verticalLayout.addWidget(self.buttonBox_operation)

        self.retranslateUi(TypeOfOperationDialog)
         # Cancel button closes dialog
        QtCore.QMetaObject.connectSlotsByName(TypeOfOperationDialog)
    
    def retranslateUi(self, TypeOfOperationDialog):
        _translate = QtCore.QCoreApplication.translate
        TypeOfOperationDialog.setWindowTitle(_translate("TypeOfOperationDialog", "Operation Type"))
        self.operation_label.setText(_translate("TypeOfOperationDialog", "Type of Operation"))
        #self.operation_select.setItemText(0, _translate("TypeOfOperationDialog", ""))
        #self.operation_select.setItemText(1, _translate("TypeOfOperationDialog", "Abnormal and Emergency Procedures"))
        self.select_operation.setText(_translate("TypeOfOperationDialog", "Select"))
        self.operation.setText(_translate("TypeOfOperationDialog", "Type of Operation"))
        self.operation_enter.setPlaceholderText(_translate("TypeOfOperationDialog", "Enter Type of Operation"))
        self.select_operation_2.setText(_translate("TypeOfOperationDialog", "Select"))
        self.missionTypeLabel.setText(_translate("TypeOfOperationDialog", "Type of Mission"))
        self.missionLineEdit.setPlaceholderText(_translate("TypeOfOperationDialog", "Enter Type of Mission "))
        self.selectMission.setText(_translate("TypeOfOperationDialog", "Select"))


