# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'warning_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_warningContainer(object):
    def setupUi(self, warningContainer):
        warningContainer.setObjectName("warningContainer")
        warningContainer.resize(280,280)
        warningContainer.setTabletTracking(False)
        warningContainer.setAcceptDrops(False)
        #warningContainer.setWindowTitle("")
        warningContainer.setStyleSheet("border-color: 3px solid red;")
        #warningContainer.setWindowFilePath("")
        warningContainer.setInputMethodHints(QtCore.Qt.ImhNone)
        self.verticalLayout = QtWidgets.QVBoxLayout(warningContainer)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout.setContentsMargins(0,0,0,0)
        self.WarningFrame = QtWidgets.QFrame(warningContainer)
        self.WarningFrame.setStyleSheet("QFrame {\n"
"    border: 3px solid red;\n"
"}\n"
"")
        self.WarningFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.WarningFrame.setMinimumSize(280,280)
        self.WarningFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.WarningFrame.setObjectName("WarningFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.WarningFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.orderNoWidget = QtWidgets.QWidget(self.WarningFrame)
        self.orderNoWidget.setObjectName("orderNoWidget")
        self.orderNoWidget.setMaximumSize(280,30)
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.orderNoWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout.setContentsMargins(0,0,0,0)
        self.orderNoLabel = QtWidgets.QLabel(self.orderNoWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.orderNoLabel.setFont(font)
        self.orderNoLabel.setStyleSheet("QLabel {\n"
"\n"
"        border: none;\n"
"   \n"
"}")
        self.orderNoLabel.setObjectName("orderNoLabel")
        self.horizontalLayout.addWidget(self.orderNoLabel)
        self.orderNo = QtWidgets.QLabel(self.orderNoWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.orderNo.setFont(font)
        self.orderNo.setStyleSheet("QLabel {\n"
"\n"
"        border: none;\n"
"   \n"
"}")
        self.orderNo.setObjectName("orderNo")
        self.horizontalLayout.addWidget(self.orderNo)
        self.verticalLayout_2.addWidget(self.orderNoWidget)
        self.flightPhaseWarningWidget = QtWidgets.QWidget(self.WarningFrame)
        self.flightPhaseWarningWidget.setObjectName("flightPhaseWarningWidget")
        self.flightPhaseWarningWidget.setMaximumSize(280,30)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.flightPhaseWarningWidget)
        self.horizontalLayout_2.setContentsMargins(0,0,0,0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.inFlightPhaselabel = QtWidgets.QLabel(self.flightPhaseWarningWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.inFlightPhaselabel.setFont(font)
        self.inFlightPhaselabel.setStyleSheet("QLabel {\n"
"\n"
"        border: none;\n"
"   \n"
"}")
        self.inFlightPhaselabel.setObjectName("inFlightPhaselabel")
        self.horizontalLayout_2.addWidget(self.inFlightPhaselabel)
        self.flightPhaseWarning = QtWidgets.QLabel(self.flightPhaseWarningWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.flightPhaseWarning.setFont(font)
        self.flightPhaseWarning.setStyleSheet("QLabel {\n"
"\n"
"        border: none;\n"
"   \n"
"}")
        self.flightPhaseWarning.setObjectName("flightPhaseWarning")
        self.horizontalLayout_2.addWidget(self.flightPhaseWarning)
        self.verticalLayout_2.addWidget(self.flightPhaseWarningWidget)
        # Procedure Widget with horizontal layout
        self.procedureWidget = QtWidgets.QWidget(self.WarningFrame)
        self.procedureWidget.setObjectName("procedureWidget")
        self.procedureWidget.setMaximumSize(280, 50)
        self.horizontalLayout_procedure = QtWidgets.QHBoxLayout(self.procedureWidget)
        self.horizontalLayout_procedure.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_procedure.setObjectName("horizontalLayout_procedure")

        # Bold Procedure Label
        self.procedureLabel = QtWidgets.QLabel(self.procedureWidget)
       
        self.procedureLabel.setStyleSheet("QLabel {\n"
"        border: none;\n"
"}")
        self.procedureLabel.setObjectName("procedureLabel")
        self.procedureLabel.setText("Procedure:")  # Text set to "Procedure"
        self.horizontalLayout_procedure.addWidget(self.procedureLabel)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.inFlightPhaselabel.setFont(font)

        # Dummy text label next to Procedure
        self.procedureText = QtWidgets.QLabel(self.procedureWidget)
        font_bold = QtGui.QFont()
        font_bold.setFamily("Segoe UI")
        font_bold.setBold(True)
        font_bold.setWeight(200)
        font_bold.setPointSize(9)

        #self.procedureLabel.setFont(font_bold)
        self.procedureText.setFont(font_bold)  # Same font as others
        self.procedureText.setStyleSheet("QLabel {\n"
"        border: none;\n"
"}")
        self.procedureText.setObjectName("procedureText")
        self.procedureText.setText("")  # Dummy text set
        self.horizontalLayout_procedure.addWidget(self.procedureText)

  # Add the Procedure widget to the vertical layout
        self.verticalLayout_2.addWidget(self.procedureWidget)
        self.missingSystemsLabel = QtWidgets.QLabel(self.WarningFrame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.missingSystemsLabel.setFont(font)
        self.missingSystemsLabel.setStyleSheet("QLabel {\n"
"\n"
"        border: none;\n"
"   \n"
"}")
        self.missingSystemsLabel.setObjectName("missingSystemsLabel")
        self.missingSystemsLabel.setMaximumSize(280,30)
        self.verticalLayout_2.addWidget(self.missingSystemsLabel)
        self.systemsWarning = QtWidgets.QLabel(self.WarningFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.systemsWarning.sizePolicy().hasHeightForWidth())
        self.systemsWarning.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.systemsWarning.setFont(font)
        self.systemsWarning.setStyleSheet("QLabel {\n"
"\n"
"        border: none;\n"
"   \n"
"}\n"
"")
        self.systemsWarning.setFrameShape(QtWidgets.QFrame.Box)
        self.systemsWarning.setFrameShadow(QtWidgets.QFrame.Plain)
        self.systemsWarning.setLineWidth(0)
        self.systemsWarning.setMidLineWidth(0)
        self.systemsWarning.setScaledContents(False)
        self.systemsWarning.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.systemsWarning.setWordWrap(True)
        self.systemsWarning.setIndent(-1)
        self.systemsWarning.setObjectName("systemsWarning")
        self.verticalLayout_2.addWidget(self.systemsWarning)
        self.verticalLayout.addWidget(self.WarningFrame)

        self.retranslateUi(warningContainer)
        QtCore.QMetaObject.connectSlotsByName(warningContainer)

    def retranslateUi(self, warningContainer):
        _translate = QtCore.QCoreApplication.translate
        self.orderNoLabel.setText(_translate("warningContainer", "<html><head/><body><p><span style=\" font-size:9pt;\"> Step Order No.</span></p></body></html>"))
        self.orderNo.setText(_translate("warningContainer", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\"></span></p></body></html>"))
        self.inFlightPhaselabel.setText(_translate("warningContainer", "<html><head/><body><p><span style=\" font-size:9pt;\">Flight Phase</span></p></body></html>"))
        self.flightPhaseWarning.setText(_translate("warningContainer", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\"></span></p></body></html>"))
        self.missingSystemsLabel.setText(_translate("warningContainer", "<html><head/><body><p><span style=\" font-size:9pt;\">Missing Systems</span></p></body></html>"))
        self.systemsWarning.setText(_translate("warningContainer", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">                                                                                                                                                                                                       Dummy2                                                                                                                                                                                                                    Dummy3                                                                                                                                                                                                                                  </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
